// Didaktisches Grundmodell (Entwurf 2026-10-05): Stundenmodelle mit ihren Phasen.
export const STUNDEN_MODELLE = [
  { key: 'induktiv', name: 'Induktive Erarbeitung', phasen: ['Problem/Phänomen begegnen', 'Beobachten & erkunden', 'Vermutungen bilden', 'Vermutungen prüfen', 'Regel formulieren', 'Anwenden & sichern', 'Rückblick Erkenntnisweg'] },
  { key: 'deduktiv', name: 'Deduktive Erarbeitung', phasen: ['Vorwissen aktivieren / Ausgangsfrage', 'Regel einführen', 'Verstehen & klären', 'Angeleitetes Anwenden', 'Selbstständiger Transfer', 'Ergebnis sichern'] },
  { key: 'uebung_kurz', name: 'Individuelle Übung · kurz', phasen: ['Übungsfokus klären', 'Individuell üben', 'Lernstand kurz prüfen'] },
  { key: 'uebung_mittel', name: 'Individuelle Übung · mittel', phasen: ['Übungsfokus klären', 'Individuelle Arbeitsphase', 'Rückmeldung / Selbstkontrolle', 'Nächste Schritte'] },
  { key: 'uebung_lang', name: 'Individuelle Übung · lang', phasen: ['Arbeitsplan & Orientierung', 'Längere Übungszeit', 'Kontrolle & Korrektur', 'Abschlussbilanz'] },
  { key: 'wiederholung', name: 'Wiederholung', phasen: ['Vorwissen reaktivieren', 'Lücken bestimmen', 'Wiederholen & üben', 'Sicherheit überprüfen', 'Weiterführende Aufgabe', 'Abschlussreflexion'] },
  { key: 'vertieft', name: 'Vertiefte Übung', phasen: ['Aufgabe & Ziel klären', 'Problem erschließen', 'Lösungsideen entwickeln', 'Produkt erstellen', 'Vergleichen & präsentieren', 'Transfer reflektieren'] },
  { key: 'diagnose_kurz', name: 'Diagnose · kurz', phasen: ['Anlass & Kriterien klären', 'Lernstand erheben', 'Rückmelden / einordnen'] },
  { key: 'diagnose_mittel', name: 'Diagnose · mittel', phasen: ['Kriterien transparent machen', 'Lernstand erheben', 'Auswerten', 'Nächste Schritte'] },
  { key: 'diagnose_lang', name: 'Diagnose · lang', phasen: ['Ziel & Kriterien klären', 'Nachweise sammeln', 'Auswerten', 'Konsequenzen festlegen'] },
];

// 1 = passt hervorragend … 5 = passt nicht
export const PASSUNG = {
  1: { label: 'Passt hervorragend', cls: 'bg-green-600 text-white' },
  2: { label: 'Passt gut', cls: 'bg-green-200 text-green-900' },
  3: { label: 'Kann passen', cls: 'bg-yellow-200 text-yellow-900' },
  4: { label: 'Eher unpassend', cls: 'bg-orange-200 text-orange-900' },
  5: { label: 'Passt nicht', cls: 'bg-red-200 text-red-900' },
};

export const BEITRAG = { kern: 'Kernbeitrag', teil: 'Teilbeitrag', bedingt: 'Bedingt' };

// Probe-Einordnung, Schlüssel = Methodenname. phasen: { Phasenname: beitrag }
export const EINORDNUNG_PROBE = {
  'Informierender Unterrichtseinstieg': {
    induktiv: { passung: 3, phasen: { 'Problem/Phänomen begegnen': 'bedingt' }, hinweis: 'Nur den Ablauf erklären, die Erkenntnis nicht vorwegnehmen. Der Überraschungsmoment hat Vorrang.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Ziel, Regel und Ablauf einordnen.' },
    uebung_kurz: { passung: 3, phasen: { 'Übungsfokus klären': 'teil' }, hinweis: 'Eine knappe Zielklärung reicht.' },
    uebung_mittel: { passung: 2, phasen: { 'Übungsfokus klären': 'kern' }, hinweis: 'Aufgabenfolge, Wahlmöglichkeiten und Kontrollwege erklären.' },
    uebung_lang: { passung: 1, phasen: { 'Arbeitsplan & Orientierung': 'kern' }, hinweis: 'Bei Stationenlernen fast notwendig: Stationen, Zeit, Wechsel, Material, Ergebnis.' },
    wiederholung: { passung: 3, phasen: { 'Vorwissen reaktivieren': 'teil' }, hinweis: 'Sinnvoll bei Wahlaufgaben oder besonderem Ablauf.' },
    vertieft: { passung: 2, phasen: { 'Aufgabe & Ziel klären': 'teil' }, hinweis: 'Klärt Produkt und Zusammenarbeit, ersetzt aber nicht die Erschließung des Problems.' },
    diagnose_kurz: { passung: 2, phasen: { 'Anlass & Kriterien klären': 'kern' }, hinweis: 'Transparent machen, was erhoben wird und wozu.' },
    diagnose_mittel: { passung: 1, phasen: { 'Kriterien transparent machen': 'kern' }, hinweis: 'Ablauf und Kriterien erklären, ohne Lösungen vorwegzunehmen.' },
    diagnose_lang: { passung: 1, phasen: { 'Ziel & Kriterien klären': 'kern' }, hinweis: 'Bei mehreren Teilen oder Stationen fast notwendig.' },
  },
  'Stummer Impuls': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'bedingt' }, hinweis: 'Idealer überraschender Ausgangspunkt. Das Erkunden deckt er nur ab, wenn gezielte Beobachtungsaufträge folgen.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil' }, hinweis: 'Kann eine Leitfrage aufwerfen. Weniger passend, wenn die Stunde mit einer klaren Erklärung beginnt.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Höchstens als sehr kurzer Erinnerungsreiz, sonst kostet er Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Kann einen thematischen Rahmen setzen, ist aber kein Teil des Übens.' },
    uebung_lang: { passung: 3, phasen: { 'Arbeitsplan & Orientierung': 'bedingt' }, hinweis: 'Kann eine Anwendungssituation eröffnen, ersetzt aber nicht die Erklärung des Ablaufs.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Macht sichtbar, was erinnert wird und was unklar ist.' },
    vertieft: { passung: 2, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'teil' }, hinweis: 'Eröffnet einen Fall oder Konflikt als Ausgangspunkt für Teamarbeit.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Nur mit klarer Frage und nachvollziehbaren Kriterien als Diagnoseaufgabe nutzbar.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Als gemeinsamer Ausgangsreiz für eine Erhebung möglich.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Trägt eine umfassende Evaluation kaum, allenfalls als Einstieg in eine Teilaufgabe.' },
  },
  'Provokante These': {
    induktiv: { passung: 2, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Vermutungen bilden': 'teil' }, hinweis: 'Erzeugt Widerspruch und damit Fragebedarf. Die These darf die Regel nicht schon verraten.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern', 'Selbstständiger Transfer': 'bedingt' }, hinweis: 'Gute Ausgangsfrage, die die Regel anschließend klärt. Am Ende als Prüfstein für Transfer nutzbar.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Die Diskussion verbraucht die knappe Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Nur als kurzer Aufhänger, ohne ausführliche Debatte.' },
    uebung_lang: { passung: 4, phasen: { 'Arbeitsplan & Orientierung': 'bedingt' }, hinweis: 'Kann motivieren, trägt aber nichts zur Orientierung bei.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Fehlvorstellungen werden beim Widerlegen sichtbar.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Ein starker Fall für die Teamarbeit. Am Ende wird die These erneut bewertet.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Zustimmung oder Ablehnung mit Begründung zeigt das Verständnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Als schriftliche Stellungnahme mit Kriterien nutzbar.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Als eine Teilaufgabe zur Argumentationsfähigkeit.' },
  },
  'Blitzlicht': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'teil', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Sammelt Vermutungen schnell ein oder schließt mit einem Rückblick ab.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil', 'Ergebnis sichern': 'bedingt' }, hinweis: 'Kurzer Stimmungs- oder Vorwissensabgleich, keine inhaltliche Sicherung.' },
    uebung_kurz: { passung: 3, phasen: { 'Lernstand kurz prüfen': 'teil' }, hinweis: 'Schnelle Selbsteinschätzung am Ende.' },
    uebung_mittel: { passung: 2, phasen: { 'Nächste Schritte': 'kern', 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Jeder benennt, wo er steht und was als Nächstes kommt.' },
    uebung_lang: { passung: 2, phasen: { 'Abschlussbilanz': 'kern' }, hinweis: 'Ritualisierter Abschluss einer langen Arbeitsphase.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'teil', 'Abschlussreflexion': 'kern' }, hinweis: 'Zeigt zu Beginn den Stand und am Ende den Zugewinn.' },
    vertieft: { passung: 2, phasen: { 'Transfer reflektieren': 'kern' }, hinweis: 'Reflexion der Teamarbeit und des Erkenntnisgewinns.' },
    diagnose_kurz: { passung: 2, phasen: { 'Rückmelden / einordnen': 'kern' }, hinweis: 'Selbsteinschätzung als Ergänzung zur Erhebung.' },
    diagnose_mittel: { passung: 3, phasen: { 'Nächste Schritte': 'teil' }, hinweis: 'Nur Selbsteinschätzung, kein belastbarer Nachweis.' },
    diagnose_lang: { passung: 4, phasen: { 'Konsequenzen festlegen': 'bedingt' }, hinweis: 'Zu oberflächlich für eine umfassende Diagnose.' },
  },
  'Brainstorming / Mindmap': {
    induktiv: { passung: 2, phasen: { 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'kern' }, hinweis: 'Sammelt Beobachtungen und Ideen, die Mindmap ordnet sie zu ersten Mustern.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern', 'Ergebnis sichern': 'teil' }, hinweis: 'Aktiviert Vorwissen. Als Mindmap zur Sicherung der Begriffsstruktur geeignet.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Höchstens als schnelle Begriffssammlung vorab.' },
    uebung_lang: { passung: 4, phasen: { 'Arbeitsplan & Orientierung': 'bedingt' }, hinweis: 'Trägt kaum zur Orientierung bei.' },
    wiederholung: { passung: 1, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil', 'Abschlussreflexion': 'bedingt' }, hinweis: 'Die Mindmap macht Zusammenhänge und fehlende Äste sichtbar.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'kern', 'Problem erschließen': 'teil' }, hinweis: 'Ideensammlung im Team vor der Produktion.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Eine Einzel-Mindmap zeigt die Wissensstruktur.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Braucht klare Kriterien für die Auswertung.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Vorher-Nachher-Mindmap als Lernnachweis.' },
  },
  'Vertieftes Üben im Team': {
    induktiv: { passung: 4, phasen: { 'Vermutungen prüfen': 'bedingt', 'Anwenden & sichern': 'bedingt' }, hinweis: 'Zu umfangreich für eine Erarbeitungsstunde, allenfalls als Anwendungsteil.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'teil', 'Angeleitetes Anwenden': 'bedingt' }, hinweis: 'Kann den Transfer übernehmen, wenn die Regel gesichert ist.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Teamarbeit statt individueller Übung, nur in verkürzter Form.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Möglich, wenn kooperatives Üben gewünscht ist.' },
    wiederholung: { passung: 3, phasen: { 'Wiederholen & üben': 'teil', 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Sinnvoll als weiterführender Teil einer Wiederholung.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'kern', 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'kern', 'Produkt erstellen': 'kern', 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Trägt die ganze Stunde. Das Preset bestimmt den Ablauf der Phasen.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 5, phasen: {}, hinweis: 'Gruppenprodukte zeigen keinen individuellen Lernstand.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Nur mit zusätzlicher Einzelleistung als Nachweis nutzbar.' },
  },
  'Kartenabfrage': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'kern', 'Regel formulieren': 'teil' }, hinweis: 'Das Clustern der Karten führt zur Regel hin.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Strukturierte Vorwissenserhebung vor der Erklärung.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig für kurze Übungen.' },
    uebung_mittel: { passung: 4, phasen: { 'Nächste Schritte': 'bedingt' }, hinweis: 'Allenfalls zum Sammeln offener Fragen.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Sammelt Schwierigkeiten und Erkenntnisse am Ende.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'kern' }, hinweis: 'Anonyme Karten machen Unsicherheiten sichtbar.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'teil', 'Vergleichen & präsentieren': 'teil' }, hinweis: 'Ordnet Ideen oder Ergebnisse mehrerer Teams.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Gibt ein Gruppenbild, kein Einzelergebnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Auswerten': 'teil' }, hinweis: 'Gemeinsame Auswertung von Schwierigkeiten.' },
    diagnose_lang: { passung: 3, phasen: { 'Konsequenzen festlegen': 'teil' }, hinweis: 'Gemeinsames Ableiten nächster Schritte.' },
  },
  'Vertieftes Üben im Team mit Ämtern': {
    induktiv: { passung: 5, phasen: {}, hinweis: 'Ämterverteilung und Teamprozess sprengen eine Erarbeitungsstunde.' },
    deduktiv: { passung: 4, phasen: { 'Selbstständiger Transfer': 'bedingt' }, hinweis: 'Nur als ausgelagerter Transferteil, wenn die Regel bereits sicher ist.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 5, phasen: {}, hinweis: 'Die Organisation der Ämter kostet zu viel Übungszeit.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil', 'Abschlussbilanz': 'bedingt' }, hinweis: 'Möglich bei kooperativem Üben über mehrere Stunden.' },
    wiederholung: { passung: 4, phasen: { 'Weiterführende Aufgabe': 'bedingt' }, hinweis: 'Für eine Wiederholung meist zu aufwendig.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'kern', 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'kern', 'Produkt erstellen': 'kern', 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'kern' }, hinweis: 'Trägt die ganze Stunde. Die Ämter sichern Arbeitsteilung und Reflexion des Teamprozesses.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 5, phasen: {}, hinweis: 'Gruppenprodukte zeigen keinen individuellen Lernstand.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Ämter machen Einzelbeiträge sichtbar, z. B. für Sozial- und Methodenkompetenz.' },
  },
  'Positionslinie / Meinungsbarometer': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'kern', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Schüler positionieren sich zu einer Vermutung und prüfen am Ende, ob sie umziehen würden.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Macht Vorannahmen sichtbar, bevor die Regel eingeführt wird.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil', 'Nächste Schritte': 'teil' }, hinweis: 'Als Selbsteinschätzung: Wie sicher fühle ich mich?' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Schnelles, sichtbares Stimmungsbild am Ende.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'teil', 'Lücken bestimmen': 'kern' }, hinweis: 'Zeigt auf einen Blick, wo die Gruppe unsicher ist.' },
    vertieft: { passung: 2, phasen: { 'Problem erschließen': 'teil', 'Transfer reflektieren': 'kern' }, hinweis: 'Vorher-Nachher-Positionierung zeigt, ob die Teamarbeit Meinungen verändert hat.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'teil', 'Rückmelden / einordnen': 'teil' }, hinweis: 'Schnelle Selbsteinschätzung der ganzen Gruppe.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Nur mit Begründungen ein brauchbarer Nachweis.' },
    diagnose_lang: { passung: 4, phasen: { 'Konsequenzen festlegen': 'bedingt' }, hinweis: 'Zu grob für eine umfassende Diagnose.' },
  },
  'Vier-Ecken-Methode': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Jede Ecke steht für eine Vermutung. Die Gruppen sammeln Argumente und prüfen sie.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil', 'Verstehen & klären': 'bedingt' }, hinweis: 'Ecken als Antwortoptionen machen Fehlvorstellungen vor der Erklärung sichtbar.' },
    uebung_kurz: { passung: 4, phasen: { 'Lernstand kurz prüfen': 'bedingt' }, hinweis: 'Höchstens als schnelle Multiple-Choice-Abfrage im Raum.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Als bewegte Kontrollfrage mit Begründung.' },
    uebung_lang: { passung: 4, phasen: { 'Kontrolle & Korrektur': 'bedingt' }, hinweis: 'Unterbricht die lange Übungszeit eher.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Sicherheit überprüfen': 'teil' }, hinweis: 'Antwortecken zeigen schnell, welche Inhalte sitzen.' },
    vertieft: { passung: 3, phasen: { 'Problem erschließen': 'teil', 'Lösungsideen entwickeln': 'bedingt' }, hinweis: 'Kann Teams nach Position bilden, bevor die Teamarbeit beginnt.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Gute Schnelldiagnose, wenn die Ecken typische Fehler abbilden.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Ergänzt eine schriftliche Erhebung.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Liefert keine individuellen Nachweise.' },
  },
  'Think-Pair-Share': {
    induktiv: { passung: 1, phasen: { 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'kern', 'Regel formulieren': 'kern' }, hinweis: 'Jeder denkt erst allein nach, dann wird im Paar verdichtet und im Plenum zur Regel geführt.' },
    deduktiv: { passung: 2, phasen: { 'Verstehen & klären': 'kern', 'Angeleitetes Anwenden': 'teil' }, hinweis: 'Sichert das Verständnis der eingeführten Regel.' },
    uebung_kurz: { passung: 4, phasen: { 'Lernstand kurz prüfen': 'bedingt' }, hinweis: 'Für reine Übung meist zu viel Austausch.' },
    uebung_mittel: { passung: 2, phasen: { 'Individuelle Arbeitsphase': 'teil', 'Rückmeldung / Selbstkontrolle': 'kern' }, hinweis: 'Erst allein üben, dann Ergebnisse im Paar vergleichen.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'teil', 'Kontrolle & Korrektur': 'kern' }, hinweis: 'Partnerkontrolle strukturiert die Korrektur.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Wiederholen & üben': 'teil' }, hinweis: 'Gegenseitiges Erklären festigt das Wissen.' },
    vertieft: { passung: 2, phasen: { 'Problem erschließen': 'teil', 'Lösungsideen entwickeln': 'kern' }, hinweis: 'Gute Vorstufe vor der Teamarbeit.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Die Think-Phase liefert ein Einzelergebnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil', 'Auswerten': 'teil' }, hinweis: 'Paarweise Auswertung mit Kriterien möglich.' },
    diagnose_lang: { passung: 4, phasen: { 'Auswerten': 'bedingt' }, hinweis: 'Trägt eine umfassende Diagnose nicht.' },
  },
  'Demonstration / Experiment vorführen': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Beobachten & erkunden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Das Phänomen wird sichtbar. Vorher Vermutungen sammeln, damit die Beobachtung gezielt wird.' },
    deduktiv: { passung: 2, phasen: { 'Regel einführen': 'teil', 'Verstehen & klären': 'kern' }, hinweis: 'Veranschaulicht und bestätigt die eingeführte Regel.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Höchstens als kurzes Vormachen der Arbeitstechnik.' },
    uebung_lang: { passung: 3, phasen: { 'Arbeitsplan & Orientierung': 'teil' }, hinweis: 'Vormachen eines Verfahrens, das danach selbst geübt wird.' },
    wiederholung: { passung: 3, phasen: { 'Vorwissen reaktivieren': 'teil' }, hinweis: 'Erneutes Zeigen ruft Wissen wach.' },
    vertieft: { passung: 3, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'teil' }, hinweis: 'Kann den Ausgangsfall der Teamarbeit liefern.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Schüler erklären ein vorgeführtes Phänomen.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Als Erklärungsaufgabe mit Kriterien nutzbar.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls Teil einer Gesamtdiagnose.' },
  },
  'Problemaufriss / Schätzfrage': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Vermutungen bilden': 'kern' }, hinweis: 'Schätzungen erzeugen Neugier und echte Vermutungen, die später geprüft werden.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Liefert die Ausgangsfrage, die die Regel anschließend beantwortet.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Nur als sehr kurzer Aufhänger.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Setzt einen Rahmen, ist aber kein Teil des Übens.' },
    uebung_lang: { passung: 3, phasen: { 'Arbeitsplan & Orientierung': 'teil' }, hinweis: 'Kann das Ziel einer längeren Übungsreihe anschaulich machen.' },
    wiederholung: { passung: 3, phasen: { 'Vorwissen reaktivieren': 'teil' }, hinweis: 'Die Schätzung zeigt, ob Größenvorstellungen sitzen.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'kern', 'Problem erschließen': 'kern' }, hinweis: 'Ein offenes Problem ist der ideale Ausgangspunkt für Teamarbeit.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Begründete Schätzungen zeigen Vorstellungen und Strategien.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Mit Begründungsauftrag als Diagnoseaufgabe nutzbar.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls eine Teilaufgabe.' },
  },
  'Wortwolke': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'teil', 'Problem/Phänomen begegnen': 'bedingt' }, hinweis: 'Sammelt erste Ideen oder Vermutungen sichtbar. Für das eigentliche Erkunden zu oberflächlich.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Macht Vorwissen und Begriffe der Klasse in Sekunden sichtbar, an die die Regel anknüpft.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Kostet Gerätezeit, ohne zum Üben beizutragen.' },
    uebung_mittel: { passung: 4, phasen: { 'Nächste Schritte': 'bedingt' }, hinweis: 'Höchstens als kurze Abfrage „Was war schwierig?“ am Ende.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Als schnelle Bilanz nach langer Übungszeit möglich.' },
    wiederholung: { passung: 1, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Zeigt, welche Begriffe präsent sind und welche fehlen. Fehlende Kernbegriffe sind der Hinweis auf Lücken.' },
    vertieft: { passung: 3, phasen: { 'Aufgabe & Ziel klären': 'bedingt', 'Transfer reflektieren': 'teil' }, hinweis: 'Zum Einstimmen oder als Abschlussreflexion, nicht für die Teamarbeit selbst.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Schnelles Stimmungs- oder Begriffsbild der ganzen Klasse, aber anonym und ohne Begründung.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Liefert ein Gesamtbild, keine Aussage über einzelne Schüler.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Für belastbare Nachweise zu grob.' },
  },
  'Mystery / Rätsel': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Beobachten & erkunden': 'kern', 'Vermutungen bilden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Die rätselhafte Leitfrage führt die Schüler selbst zur Erkenntnis. Die Regel danach ausdrücklich formulieren lassen.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'teil' }, hinweis: 'Als Einstieg verrät es zu wenig, als Transferaufgabe nach der Regel gut geeignet.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Viel zu zeitaufwendig für eine kurze Übung.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Nur als kleines Mystery mit wenigen Karten.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Als Station oder Wahlaufgabe möglich.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Verknüpft bekanntes Wissen neu, deckt Lücken aber nicht gezielt auf.' },
    vertieft: { passung: 1, phasen: { 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'kern', 'Vergleichen & präsentieren': 'teil' }, hinweis: 'Ideal für Teams: ordnen, verknüpfen, Lösung begründen und vergleichen.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Zu lang und zu offen für eine schnelle Erhebung.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Die gelegte Struktur zeigt Vernetzungsdenken, die Auswertung ist aber aufwendig.' },
    diagnose_lang: { passung: 2, phasen: { 'Nachweise sammeln': 'kern' }, hinweis: 'Gute Leistungsaufgabe für Zusammenhangswissen, wenn Kriterien vorher feststehen.' },
  },
  'Gedankenexperiment': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Vermutungen bilden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Die Folgen durchdenken führt zur Erkenntnis. Wo möglich am realen Fall prüfen.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil', 'Selbstständiger Transfer': 'kern' }, hinweis: 'Eröffnet eine Ausgangsfrage oder prüft am Ende, ob die Regel auch im gedachten Fall trägt.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 4, phasen: { 'Nächste Schritte': 'bedingt' }, hinweis: 'Höchstens als kurzer Denkanstoß zum Abschluss.' },
    uebung_lang: { passung: 4, phasen: { 'Längere Übungszeit': 'bedingt' }, hinweis: 'Allenfalls als Zusatzaufgabe für Schnelle.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Wendet Wiederholtes auf eine neue Situation an.' },
    vertieft: { passung: 2, phasen: { 'Problem erschließen': 'kern', 'Transfer reflektieren': 'kern' }, hinweis: 'Starker Ausgangsfall oder Abschlussfrage für Teams.' },
    diagnose_kurz: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Antworten sind schwer schnell vergleichbar.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Zeigt Verständnistiefe, wenn Begründungen schriftlich vorliegen.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Als Transferteil einer größeren Leistungsaufgabe geeignet.' },
  },
  'Lehrervortrag / Input': {
    induktiv: { passung: 4, phasen: { 'Regel formulieren': 'bedingt' }, hinweis: 'Nimmt die Erkenntnis vorweg. Höchstens zum Bündeln der gefundenen Regel.' },
    deduktiv: { passung: 1, phasen: { 'Regel einführen': 'kern', 'Verstehen & klären': 'teil' }, hinweis: 'Kernmethode der Regeleinführung. Kurz halten und mit Beispielen verbinden.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Nur als knappe Erinnerung an das Verfahren.' },
    uebung_mittel: { passung: 3, phasen: { 'Übungsfokus klären': 'teil' }, hinweis: 'Kurzer Input zur Arbeitstechnik vor dem Üben.' },
    uebung_lang: { passung: 3, phasen: { 'Arbeitsplan & Orientierung': 'teil' }, hinweis: 'Erklärt Ablauf und Material.' },
    wiederholung: { passung: 3, phasen: { 'Wiederholen & üben': 'teil' }, hinweis: 'Kurze Wiederholung der Regel bei erkannten Lücken.' },
    vertieft: { passung: 4, phasen: { 'Aufgabe & Ziel klären': 'bedingt' }, hinweis: 'Nur zur Aufgabenklärung, nicht zur Problemerschließung.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Kriterien transparent machen': 'bedingt' }, hinweis: 'Nur zur Erklärung der Kriterien.' },
    diagnose_lang: { passung: 4, phasen: { 'Ziel & Kriterien klären': 'bedingt' }, hinweis: 'Nur zur Erklärung der Kriterien.' },
  },
  'Fragend-entwickelndes Unterrichtsgespräch': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'teil', 'Vermutungen prüfen': 'teil', 'Regel formulieren': 'kern' }, hinweis: 'Führt gemeinsam zur Regel. Gefahr: Die Lehrkraft lenkt zu stark.' },
    deduktiv: { passung: 2, phasen: { 'Verstehen & klären': 'kern', 'Vorwissen aktivieren / Ausgangsfrage': 'teil' }, hinweis: 'Klärt Verständnisfragen zur eingeführten Regel.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kostet Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Rückmeldung / Selbstkontrolle': 'bedingt' }, hinweis: 'Höchstens zur gemeinsamen Besprechung typischer Fehler.' },
    uebung_lang: { passung: 4, phasen: { 'Kontrolle & Korrektur': 'bedingt' }, hinweis: 'Unterbricht die individuelle Arbeit.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Gezielte Fragen decken Lücken auf.' },
    vertieft: { passung: 3, phasen: { 'Vergleichen & präsentieren': 'teil', 'Transfer reflektieren': 'teil' }, hinweis: 'Zum Auswerten der Teamergebnisse.' },
    diagnose_kurz: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Erfasst nur die Antwortenden, nicht alle.' },
    diagnose_mittel: { passung: 4, phasen: { 'Auswerten': 'bedingt' }, hinweis: 'Kein individueller Nachweis.' },
    diagnose_lang: { passung: 5, phasen: {}, hinweis: 'Trägt keine Diagnose.' },
  },
  'Partnerinterview': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'teil', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Partner tauschen Vermutungen oder den Erkenntnisweg aus.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern', 'Verstehen & klären': 'teil' }, hinweis: 'Aktiviert Vorwissen, alle kommen zu Wort.' },
    uebung_kurz: { passung: 4, phasen: { 'Lernstand kurz prüfen': 'bedingt' }, hinweis: 'Zu viel Austausch für kurze Übung.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Gegenseitiges Abfragen als Kontrolle.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Austausch über Fortschritte am Ende.' },
    wiederholung: { passung: 1, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil', 'Abschlussreflexion': 'teil' }, hinweis: 'Gegenseitiges Fragen und Erklären reaktiviert Wissen für alle.' },
    vertieft: { passung: 3, phasen: { 'Transfer reflektieren': 'teil' }, hinweis: 'Reflexion des eigenen Beitrags im Team.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Nur mit festen Fragen und Notizen auswertbar.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Partner halten Antworten nach Kriterien fest.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Kein belastbarer Einzelnachweis.' },
  },
  'Lerntempoduett': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'teil', 'Vermutungen prüfen': 'teil' }, hinweis: 'Einzelerkundung, dann Abgleich mit einem gleich schnellen Partner.' },
    deduktiv: { passung: 2, phasen: { 'Angeleitetes Anwenden': 'kern', 'Selbstständiger Transfer': 'teil' }, hinweis: 'Jeder wendet im eigenen Tempo an und bespricht dann im Paar.' },
    uebung_kurz: { passung: 4, phasen: { 'Individuell üben': 'bedingt' }, hinweis: 'Die Paarbildung braucht mehr Zeit.' },
    uebung_mittel: { passung: 1, phasen: { 'Individuelle Arbeitsphase': 'kern', 'Rückmeldung / Selbstkontrolle': 'kern' }, hinweis: 'Ideal: eigenes Tempo, Vergleich mit Partner auf gleichem Stand.' },
    uebung_lang: { passung: 1, phasen: { 'Längere Übungszeit': 'kern', 'Kontrolle & Korrektur': 'kern' }, hinweis: 'Mehrere Runden mit wechselnden Partnern möglich.' },
    wiederholung: { passung: 2, phasen: { 'Wiederholen & üben': 'kern', 'Sicherheit überprüfen': 'teil' }, hinweis: 'Differenziert nach Tempo.' },
    vertieft: { passung: 3, phasen: { 'Problem erschließen': 'teil' }, hinweis: 'Als Einzelvorbereitung vor der Teamphase.' },
    diagnose_kurz: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Das Tempo zeigt wenig über das Verständnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Die Einzelphase liefert ein auswertbares Ergebnis.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls ein Baustein.' },
  },
  'Gruppenpuzzle (Jigsaw)': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'kern', 'Regel formulieren': 'teil' }, hinweis: 'Expertengruppen erkunden Teilaspekte, die Stammgruppe fügt sie zur Regel zusammen. Zeitaufwendig.' },
    deduktiv: { passung: 2, phasen: { 'Verstehen & klären': 'kern', 'Ergebnis sichern': 'teil' }, hinweis: 'Teilaspekte der Regel werden erarbeitet und gegenseitig erklärt.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Organisation kostet zu viel Übungszeit.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Möglich, wenn verschiedene Aufgabentypen verteilt werden.' },
    wiederholung: { passung: 2, phasen: { 'Wiederholen & üben': 'kern', 'Sicherheit überprüfen': 'teil' }, hinweis: 'Jeder wiederholt einen Teil und erklärt ihn den anderen.' },
    vertieft: { passung: 2, phasen: { 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'teil' }, hinweis: 'Experten bringen Teilwissen in die Teamaufgabe ein.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Nur mit abschließender Einzelaufgabe aussagekräftig.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Die Expertenerklärung kann als Einzelnachweis dienen.' },
  },
  'Stationenlernen / Lernzirkel': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'kern' }, hinweis: 'Erkundungsstationen zu einem Phänomen. Die Regel muss danach gemeinsam formuliert werden.' },
    deduktiv: { passung: 3, phasen: { 'Angeleitetes Anwenden': 'teil', 'Selbstständiger Transfer': 'teil' }, hinweis: 'Anwendungsstationen nach der Regeleinführung.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Zu viel Organisation für kurze Übung.' },
    uebung_mittel: { passung: 3, phasen: { 'Individuelle Arbeitsphase': 'teil' }, hinweis: 'Nur mit wenigen Stationen.' },
    uebung_lang: { passung: 1, phasen: { 'Arbeitsplan & Orientierung': 'teil', 'Längere Übungszeit': 'kern', 'Kontrolle & Korrektur': 'teil' }, hinweis: 'Klassisches Format für lange, differenzierte Übungsphasen mit Laufzettel.' },
    wiederholung: { passung: 1, phasen: { 'Wiederholen & üben': 'kern', 'Sicherheit überprüfen': 'teil', 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Pflicht- und Wahlstationen decken Lücken gezielt ab.' },
    vertieft: { passung: 4, phasen: { 'Problem erschließen': 'bedingt' }, hinweis: 'Zerlegt das Problem, statt es im Team zu bearbeiten.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Diagnosestationen zu einzelnen Kompetenzen.' },
    diagnose_lang: { passung: 2, phasen: { 'Nachweise sammeln': 'kern' }, hinweis: 'Jede Station liefert einen Nachweis zu einem Teilbereich.' },
  },
  'Arbeitsteilige Gruppenarbeit': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Gruppen untersuchen verschiedene Fälle, der Vergleich führt zur Regel.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'teil' }, hinweis: 'Gruppen übertragen die Regel auf unterschiedliche Fälle.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Gruppenarbeit statt individueller Übung.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Möglich bei kooperativen Übungsaufgaben.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Gruppen wiederholen verschiedene Teilthemen.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'kern', 'Produkt erstellen': 'kern', 'Vergleichen & präsentieren': 'teil' }, hinweis: 'Verschiedene Teilprodukte werden am Ende zusammengeführt.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 5, phasen: {}, hinweis: 'Zeigt keinen individuellen Lernstand.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Nur mit Einzelbeiträgen auswertbar.' },
  },
  'Expertenrunde': {
    induktiv: { passung: 3, phasen: { 'Regel formulieren': 'teil', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Experten berichten Ergebnisse, daraus wird die Regel gebündelt.' },
    deduktiv: { passung: 3, phasen: { 'Verstehen & klären': 'teil', 'Ergebnis sichern': 'teil' }, hinweis: 'Schüler erklären Teilaspekte der Regel.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Schüler, die fertig sind, helfen als Experten.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'teil', 'Kontrolle & Korrektur': 'kern' }, hinweis: 'Expertenhilfe entlastet die Lehrkraft in langen Übungsphasen.' },
    wiederholung: { passung: 2, phasen: { 'Wiederholen & üben': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Experten beraten bei erkannten Lücken.' },
    vertieft: { passung: 2, phasen: { 'Vergleichen & präsentieren': 'kern', 'Problem erschließen': 'teil' }, hinweis: 'Teams beraten sich gegenseitig oder präsentieren Teilergebnisse.' },
    diagnose_kurz: { passung: 4, phasen: { 'Rückmelden / einordnen': 'bedingt' }, hinweis: 'Zeigt nur den Stand der Experten.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Die Erklärung als Experte zeigt Verständnis.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Expertenvortrag als Einzelnachweis.' },
  },
  'Schülerexperiment': {
    induktiv: { passung: 1, phasen: { 'Beobachten & erkunden': 'kern', 'Vermutungen prüfen': 'kern', 'Regel formulieren': 'teil' }, hinweis: 'Schüler prüfen ihre Vermutungen selbst. Vorher Hypothesen festhalten.' },
    deduktiv: { passung: 2, phasen: { 'Angeleitetes Anwenden': 'kern', 'Verstehen & klären': 'teil' }, hinweis: 'Bestätigt die Regel und macht sie greifbar.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Nur zum Üben einer Arbeitstechnik.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Als Übung experimenteller Methoden.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Ein Experiment vertieft wiederholte Inhalte.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'teil', 'Produkt erstellen': 'kern' }, hinweis: 'Teams planen und führen ein eigenes Experiment durch.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Protokoll und Deutung zeigen das Verständnis.' },
    diagnose_lang: { passung: 2, phasen: { 'Nachweise sammeln': 'kern' }, hinweis: 'Geeignet zum Nachweis experimenteller Kompetenz.' },
  },
  'Rollenspiel': {
    induktiv: { passung: 3, phasen: { 'Problem/Phänomen begegnen': 'teil', 'Beobachten & erkunden': 'teil' }, hinweis: 'Eine gespielte Situation macht ein Problem erlebbar. Die Auswertung führt zur Erkenntnis.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'kern' }, hinweis: 'Die eingeführte Regel wird in einer Situation angewendet, z. B. Gesprächsregeln.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Vorbereitung und Spiel sprengen die Zeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Nur bei sprachlichen Übungen in Kurzszenen.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Szenen in mehreren Durchgängen mit wechselnden Rollen.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Gelerntes wird in einer neuen Situation gezeigt.' },
    vertieft: { passung: 1, phasen: { 'Lösungsideen entwickeln': 'teil', 'Produkt erstellen': 'kern', 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Teams entwickeln und spielen eine Szene. Die Beobachter werten mit Kriterien aus.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig.' },
    diagnose_mittel: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Nur mit Beobachtungsbogen auswertbar.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Geeignet für kommunikative Kompetenzen, braucht klare Kriterien.' },
  },
  'Reziprokes Lesen': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'kern' }, hinweis: 'Ein Sachtext wird gemeinsam erschlossen. Die Regel daraus muss noch formuliert werden.' },
    deduktiv: { passung: 2, phasen: { 'Verstehen & klären': 'kern', 'Regel einführen': 'teil' }, hinweis: 'Die Regel wird aus einem Text erarbeitet und in der Gruppe geklärt.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 3, phasen: { 'Individuelle Arbeitsphase': 'teil' }, hinweis: 'Als Übung der Lesestrategie selbst.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'kern' }, hinweis: 'Mehrere Textabschnitte mit wechselnden Rollen.' },
    wiederholung: { passung: 3, phasen: { 'Wiederholen & üben': 'teil' }, hinweis: 'Wiederholung über einen zusammenfassenden Text.' },
    vertieft: { passung: 3, phasen: { 'Problem erschließen': 'kern' }, hinweis: 'Erschließt das Material, bevor das Team das Produkt erstellt.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Zeigt Lesekompetenz nur im Gruppenbild.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls mit Einzelzusammenfassung als Nachweis.' },
  },
  'Placemat': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'kern', 'Regel formulieren': 'teil' }, hinweis: 'Jeder notiert eigene Vermutungen, die Mitte bündelt sie zur gemeinsamen Regel.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern', 'Ergebnis sichern': 'teil' }, hinweis: 'Aktiviert Vorwissen jedes Einzelnen und sichert das Gruppenergebnis.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 4, phasen: { 'Rückmeldung / Selbstkontrolle': 'bedingt' }, hinweis: 'Höchstens zum Vergleich von Lösungswegen.' },
    uebung_lang: { passung: 4, phasen: { 'Abschlussbilanz': 'bedingt' }, hinweis: 'Kann Erkenntnisse am Ende bündeln.' },
    wiederholung: { passung: 1, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'kern' }, hinweis: 'Einzelfelder zeigen, was jeder weiß, die Mitte zeigt, was fehlt.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'kern', 'Problem erschließen': 'teil' }, hinweis: 'Strukturierte Ideensammlung, bevor das Team sich festlegt.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Die Einzelfelder liefern einen schnellen Einblick.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Einzelfelder mit Kriterien auswertbar.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls ein Baustein.' },
  },
  'Tafelbild gemeinsam entwickeln': {
    induktiv: { passung: 2, phasen: { 'Regel formulieren': 'kern', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Hält die gefundene Regel und den Weg dorthin fest.' },
    deduktiv: { passung: 1, phasen: { 'Regel einführen': 'teil', 'Ergebnis sichern': 'kern' }, hinweis: 'Klassische Sicherung der eingeführten Regel mit Beispielen.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kostet Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Nur als kurze Erinnerung an das Verfahren.' },
    uebung_lang: { passung: 4, phasen: { 'Abschlussbilanz': 'bedingt' }, hinweis: 'Höchstens zum Festhalten typischer Fehler.' },
    wiederholung: { passung: 2, phasen: { 'Wiederholen & üben': 'teil', 'Abschlussreflexion': 'teil' }, hinweis: 'Fasst das Wiederholte geordnet zusammen.' },
    vertieft: { passung: 3, phasen: { 'Vergleichen & präsentieren': 'teil' }, hinweis: 'Bündelt die Ergebnisse mehrerer Teams.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Auswerten': 'bedingt' }, hinweis: 'Nur zur gemeinsamen Besprechung der Ergebnisse.' },
    diagnose_lang: { passung: 4, phasen: { 'Konsequenzen festlegen': 'bedingt' }, hinweis: 'Nur zum Festhalten nächster Schritte.' },
  },
  'Ergebnispräsentation': {
    induktiv: { passung: 3, phasen: { 'Regel formulieren': 'teil', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Gruppen stellen ihre Befunde vor, daraus wird die Regel abgeleitet.' },
    deduktiv: { passung: 3, phasen: { 'Ergebnis sichern': 'teil' }, hinweis: 'Vorstellen von Anwendungsergebnissen.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kostet Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Rückmeldung / Selbstkontrolle': 'bedingt' }, hinweis: 'Höchstens einzelne Lösungen kurz vorstellen.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Ausgewählte Ergebnisse zum Abschluss vorstellen.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'bedingt', 'Abschlussreflexion': 'teil' }, hinweis: 'Präsentation weiterführender Aufgaben.' },
    vertieft: { passung: 1, phasen: { 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Fester Bestandteil der vertieften Übung. Vorher Feedbackkriterien festlegen.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Mit Bewertungsbogen auswertbar.' },
    diagnose_lang: { passung: 2, phasen: { 'Nachweise sammeln': 'kern', 'Auswerten': 'teil' }, hinweis: 'Geeigneter Nachweis für Präsentationskompetenz.' },
  },
  'Lückentext': {
    induktiv: { passung: 3, phasen: { 'Regel formulieren': 'teil', 'Anwenden & sichern': 'kern' }, hinweis: 'Ein Lückentext kann die gefundene Regel festhalten. Er darf die Erkenntnis aber nicht vorwegnehmen.' },
    deduktiv: { passung: 1, phasen: { 'Angeleitetes Anwenden': 'kern', 'Ergebnis sichern': 'kern' }, hinweis: 'Klassische angeleitete Anwendung und Sicherung der eingeführten Regel.' },
    uebung_kurz: { passung: 1, phasen: { 'Individuell üben': 'kern', 'Lernstand kurz prüfen': 'teil' }, hinweis: 'Schnell bearbeitet und digital sofort ausgewertet.' },
    uebung_mittel: { passung: 1, phasen: { 'Individuelle Arbeitsphase': 'kern', 'Rückmeldung / Selbstkontrolle': 'kern' }, hinweis: 'Mit automatischer Rückmeldung ideal zur Selbstkontrolle.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'kern', 'Kontrolle & Korrektur': 'teil' }, hinweis: 'Gut als Baustein, über eine lange Phase aber zu eintönig. Mit anderen Formaten mischen.' },
    wiederholung: { passung: 1, phasen: { 'Wiederholen & üben': 'kern', 'Sicherheit überprüfen': 'kern' }, hinweis: 'Fachbegriffe und Regeln werden gezielt abgerufen.' },
    vertieft: { passung: 4, phasen: { 'Problem erschließen': 'bedingt' }, hinweis: 'Zu geschlossen für die Teamarbeit, höchstens zum Sichern von Grundbegriffen.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Schnelle, auswertbare Abfrage von Begriffen und Regeln.' },
    diagnose_mittel: { passung: 2, phasen: { 'Lernstand erheben': 'kern', 'Auswerten': 'teil' }, hinweis: 'Die digitale Auswertung zeigt typische Fehler sofort.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Erfasst nur Wissen, kein Verständnis oder Anwenden.' },
  },
  'Reihenfolge / Sortierung': {
    induktiv: { passung: 2, phasen: { 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'teil', 'Anwenden & sichern': 'teil' }, hinweis: 'Das Ordnen von Beispielen kann ein Muster sichtbar machen.' },
    deduktiv: { passung: 2, phasen: { 'Angeleitetes Anwenden': 'kern', 'Ergebnis sichern': 'teil' }, hinweis: 'Ein eingeführtes Verfahren wird in die richtige Schrittfolge gebracht.' },
    uebung_kurz: { passung: 1, phasen: { 'Individuell üben': 'kern' }, hinweis: 'Kurz, klar und digital sofort ausgewertet.' },
    uebung_mittel: { passung: 1, phasen: { 'Individuelle Arbeitsphase': 'kern', 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Gut für Abläufe, Chronologien und Verfahrensschritte.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'teil', 'Kontrolle & Korrektur': 'teil' }, hinweis: 'Ein Baustein unter mehreren Übungsformaten.' },
    wiederholung: { passung: 1, phasen: { 'Wiederholen & üben': 'kern', 'Sicherheit überprüfen': 'teil' }, hinweis: 'Ruft Abläufe und Zusammenhänge gezielt ab.' },
    vertieft: { passung: 3, phasen: { 'Problem erschließen': 'teil', 'Lösungsideen entwickeln': 'bedingt' }, hinweis: 'Kann ein Problem strukturieren, ist aber kein eigenes Teamprodukt.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Zeigt schnell, ob Abläufe verstanden sind.' },
    diagnose_mittel: { passung: 2, phasen: { 'Lernstand erheben': 'kern', 'Auswerten': 'teil' }, hinweis: 'Fehlerhafte Reihenfolgen machen Fehlvorstellungen sichtbar.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Ein Baustein, kein umfassender Nachweis.' },
  },
  'Begriffe zuordnen': {
    induktiv: { passung: 4, phasen: { 'Anwenden & sichern': 'teil' }, hinweis: 'Gibt die Zuordnung vor und nimmt damit die Erkenntnis vorweg. Erst nach der Regel sinnvoll.' },
    deduktiv: { passung: 1, phasen: { 'Angeleitetes Anwenden': 'kern', 'Ergebnis sichern': 'teil' }, hinweis: 'Festigt Fachbegriffe direkt nach der Einführung.' },
    uebung_kurz: { passung: 1, phasen: { 'Individuell üben': 'kern', 'Lernstand kurz prüfen': 'teil' }, hinweis: 'Schnell bearbeitet und digital sofort ausgewertet.' },
    uebung_mittel: { passung: 1, phasen: { 'Individuelle Arbeitsphase': 'kern', 'Rückmeldung / Selbstkontrolle': 'kern' }, hinweis: 'Mit automatischer Rückmeldung ideal zur Selbstkontrolle.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'teil', 'Kontrolle & Korrektur': 'teil' }, hinweis: 'Guter Baustein, allein über eine lange Phase zu eintönig.' },
    wiederholung: { passung: 1, phasen: { 'Wiederholen & üben': 'kern', 'Sicherheit überprüfen': 'kern' }, hinweis: 'Ruft Begriffe und Definitionen gezielt ab.' },
    vertieft: { passung: 4, phasen: { 'Problem erschließen': 'bedingt' }, hinweis: 'Zu geschlossen, höchstens zum Sichern von Grundbegriffen vorab.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Schnelle, eindeutig auswertbare Begriffsabfrage.' },
    diagnose_mittel: { passung: 2, phasen: { 'Lernstand erheben': 'kern', 'Auswerten': 'teil' }, hinweis: 'Falsche Paare zeigen typische Verwechslungen.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Erfasst nur Wissen, kein Anwenden.' },
  },
  'Digitaler Kurztest': {
    induktiv: { passung: 4, phasen: { 'Anwenden & sichern': 'bedingt' }, hinweis: 'Nur als kurze Abschlusskontrolle der gefundenen Regel.' },
    deduktiv: { passung: 3, phasen: { 'Ergebnis sichern': 'teil', 'Angeleitetes Anwenden': 'bedingt' }, hinweis: 'Prüft am Ende, ob die Regel verstanden ist.' },
    uebung_kurz: { passung: 2, phasen: { 'Lernstand kurz prüfen': 'kern', 'Individuell üben': 'teil' }, hinweis: 'Schließt eine kurze Übung mit klarer Rückmeldung ab.' },
    uebung_mittel: { passung: 2, phasen: { 'Rückmeldung / Selbstkontrolle': 'kern' }, hinweis: 'Zeigt nach der Übung, was sitzt.' },
    uebung_lang: { passung: 2, phasen: { 'Kontrolle & Korrektur': 'kern', 'Abschlussbilanz': 'teil' }, hinweis: 'Gute Zwischen- oder Abschlusskontrolle.' },
    wiederholung: { passung: 1, phasen: { 'Lücken bestimmen': 'kern', 'Sicherheit überprüfen': 'kern' }, hinweis: 'Zu Beginn deckt er Lücken auf, am Ende zeigt er den Zugewinn.' },
    vertieft: { passung: 5, phasen: {}, hinweis: 'Kein Format für Teamarbeit.' },
    diagnose_kurz: { passung: 1, phasen: { 'Lernstand erheben': 'kern', 'Rückmelden / einordnen': 'teil' }, hinweis: 'Kernformat der Schnelldiagnose mit sofortiger Auswertung.' },
    diagnose_mittel: { passung: 1, phasen: { 'Lernstand erheben': 'kern', 'Auswerten': 'kern' }, hinweis: 'Die Auswertung zeigt Einzel- und Gruppenbild.' },
    diagnose_lang: { passung: 2, phasen: { 'Nachweise sammeln': 'kern' }, hinweis: 'Belastbarer Wissensnachweis, für Anwenden mit offenen Aufgaben ergänzen.' },
  },
  'Fallstudie': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Beobachten & erkunden': 'kern', 'Regel formulieren': 'teil' }, hinweis: 'Aus dem konkreten Fall wird das Allgemeine abgeleitet.' },
    deduktiv: { passung: 2, phasen: { 'Selbstständiger Transfer': 'kern' }, hinweis: 'Ideal, um die Regel an einem echten Fall anzuwenden.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Viel zu umfangreich.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Nur als sehr kurzer Minifall.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Als anspruchsvolle Anwendungsaufgabe möglich.' },
    wiederholung: { passung: 3, phasen: { 'Weiterführende Aufgabe': 'kern' }, hinweis: 'Verknüpft Wiederholtes an einem neuen Fall.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'kern', 'Vergleichen & präsentieren': 'teil' }, hinweis: 'Trägt die Teamarbeit: Fall analysieren, Lösung begründen, vergleichen.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Zu lang für eine Schnelldiagnose.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Zeigt Anwendungskompetenz, wenn Kriterien feststehen.' },
    diagnose_lang: { passung: 2, phasen: { 'Nachweise sammeln': 'kern' }, hinweis: 'Gute Leistungsaufgabe für Transfer und Urteilen.' },
  },
  'Fishbowl-Diskussion': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'teil', 'Vermutungen prüfen': 'teil' }, hinweis: 'Vermutungen werden im Innenkreis öffentlich abgewogen.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'teil' }, hinweis: 'Diskussion über die Anwendung der Regel auf einen strittigen Fall.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 5, phasen: {}, hinweis: 'Kostet Übungszeit.' },
    uebung_lang: { passung: 4, phasen: { 'Abschlussbilanz': 'bedingt' }, hinweis: 'Allenfalls zum Austausch über Erfahrungen.' },
    wiederholung: { passung: 4, phasen: { 'Weiterführende Aufgabe': 'bedingt' }, hinweis: 'Nur bei strittigen Wiederholungsthemen.' },
    vertieft: { passung: 1, phasen: { 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'kern' }, hinweis: 'Teamvertreter diskutieren ihre Lösungen, der Außenkreis beobachtet mit Kriterien.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Erfasst nur die Sprechenden.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Mit Beobachtungsbogen Nachweis für Diskussionskompetenz.' },
  },
  'Flipped Classroom': {
    induktiv: { passung: 4, phasen: { 'Problem/Phänomen begegnen': 'bedingt' }, hinweis: 'Das Vorab-Video verrät meist die Erkenntnis. Höchstens als Phänomen ohne Erklärung.' },
    deduktiv: { passung: 1, phasen: { 'Regel einführen': 'kern', 'Angeleitetes Anwenden': 'kern', 'Selbstständiger Transfer': 'teil' }, hinweis: 'Die Regel kommt zu Hause, die Stunde gehört dem Anwenden.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Lohnt den Aufwand für kurze Übungen nicht.' },
    uebung_mittel: { passung: 2, phasen: { 'Individuelle Arbeitsphase': 'kern' }, hinweis: 'Mehr Übungszeit im Unterricht, wenn alle vorbereitet sind.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'kern' }, hinweis: 'Schafft Raum für lange, betreute Übungsphasen.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Wiederholen & üben': 'teil' }, hinweis: 'Wiederholungsvideo zu Hause, Lücken in der Stunde schließen.' },
    vertieft: { passung: 2, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'teil' }, hinweis: 'Grundlagen vorab, damit die Stunde der Teamarbeit gehört.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Kurzer Check, ob die Vorbereitung verstanden wurde.' },
    diagnose_mittel: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Kein eigenes Diagnoseformat.' },
    diagnose_lang: { passung: 5, phasen: {}, hinweis: 'Trägt keine Diagnose.' },
  },
  'Galeriegang / Museumsrundgang': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'teil', 'Regel formulieren': 'teil' }, hinweis: 'Vergleich mehrerer Gruppenbefunde führt zum gemeinsamen Muster.' },
    deduktiv: { passung: 3, phasen: { 'Ergebnis sichern': 'teil' }, hinweis: 'Anwendungsergebnisse werden betrachtet und verglichen.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig.' },
    uebung_mittel: { passung: 4, phasen: { 'Rückmeldung / Selbstkontrolle': 'bedingt' }, hinweis: 'Höchstens als kurzer Rundgang mit Lösungsvergleich.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Ergebnisse einer langen Phase sichtbar machen.' },
    wiederholung: { passung: 3, phasen: { 'Wiederholen & üben': 'teil' }, hinweis: 'Plakate zu Teilthemen wiederholen den Stoff im Umlauf.' },
    vertieft: { passung: 1, phasen: { 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Teamprodukte werden ausgestellt und mit Kriterien kommentiert.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Auswerten': 'bedingt' }, hinweis: 'Peer-Kommentare liefern nur ein grobes Bild.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Produkte und Kommentare als Nachweis, mit Bewertungsbogen.' },
  },
  'Insert-Methode': {
    induktiv: { passung: 3, phasen: { 'Beobachten & erkunden': 'kern' }, hinweis: 'Erschließt einen Sachtext genau, die Regel muss danach formuliert werden.' },
    deduktiv: { passung: 2, phasen: { 'Verstehen & klären': 'kern' }, hinweis: 'Markiert Bekanntes, Neues und Unklares im Regeltext.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 3, phasen: { 'Individuelle Arbeitsphase': 'teil' }, hinweis: 'Als Übung der Lesestrategie selbst.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Mehrere Texte nacheinander bearbeiten.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'teil', 'Lücken bestimmen': 'kern' }, hinweis: 'Fragezeichen zeigen genau, was unklar ist.' },
    vertieft: { passung: 3, phasen: { 'Problem erschließen': 'teil' }, hinweis: 'Erschließt Material vor der Teamarbeit.' },
    diagnose_kurz: { passung: 4, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Selbsteinschätzung, kein Nachweis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Markierungen zeigen Vorwissen und Unsicherheiten.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls ein Baustein.' },
  },
  'Marktplatz der Ideen': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'teil', 'Vermutungen prüfen': 'teil' }, hinweis: 'Verschiedene Erklärungsideen werden an Ständen vorgestellt und geprüft.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'teil' }, hinweis: 'Präsentation unterschiedlicher Anwendungsfälle.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig.' },
    uebung_mittel: { passung: 5, phasen: {}, hinweis: 'Kostet Übungszeit.' },
    uebung_lang: { passung: 4, phasen: { 'Abschlussbilanz': 'bedingt' }, hinweis: 'Nur zum Vorstellen ausgewählter Ergebnisse.' },
    wiederholung: { passung: 3, phasen: { 'Wiederholen & üben': 'teil' }, hinweis: 'Stände zu Teilthemen als bewegte Wiederholung.' },
    vertieft: { passung: 1, phasen: { 'Vergleichen & präsentieren': 'kern', 'Lösungsideen entwickeln': 'teil' }, hinweis: 'Teams präsentieren an Ständen und holen Rückmeldungen ein.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 4, phasen: { 'Auswerten': 'bedingt' }, hinweis: 'Gibt kein Einzelbild.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Standpräsentation als Nachweis, mit Kriterien.' },
  },
  'Merksatz formulieren': {
    induktiv: { passung: 1, phasen: { 'Regel formulieren': 'kern', 'Anwenden & sichern': 'teil' }, hinweis: 'Die Schüler bringen ihre Erkenntnis selbst auf den Punkt.' },
    deduktiv: { passung: 2, phasen: { 'Ergebnis sichern': 'kern' }, hinweis: 'Die Regel in eigenen Worten sichern.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Nur als kurze Erinnerung an die Regel.' },
    uebung_mittel: { passung: 3, phasen: { 'Nächste Schritte': 'teil' }, hinweis: 'Am Ende festhalten, worauf man achten muss.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Bündelt die Erkenntnisse einer langen Übung.' },
    wiederholung: { passung: 2, phasen: { 'Abschlussreflexion': 'kern', 'Vorwissen reaktivieren': 'teil' }, hinweis: 'Zeigt, ob die Regel sicher formuliert werden kann.' },
    vertieft: { passung: 3, phasen: { 'Transfer reflektieren': 'teil' }, hinweis: 'Erkenntnis der Teamarbeit verdichten.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Ein selbst formulierter Merksatz zeigt Verständnis schnell.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Mit Kriterien auswertbar.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Zu knapp für einen umfassenden Nachweis.' },
  },
  'Peer Instruction': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'kern', 'Vermutungen prüfen': 'kern' }, hinweis: 'Abstimmen, diskutieren, neu abstimmen: Vermutungen werden geschärft.' },
    deduktiv: { passung: 1, phasen: { 'Verstehen & klären': 'kern', 'Angeleitetes Anwenden': 'teil' }, hinweis: 'Konzeptfragen sichern das Verständnis der Regel.' },
    uebung_kurz: { passung: 3, phasen: { 'Lernstand kurz prüfen': 'teil' }, hinweis: 'Eine Konzeptfrage als kurzer Check.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Klärt typische Fehler nach der Übung.' },
    uebung_lang: { passung: 4, phasen: { 'Kontrolle & Korrektur': 'bedingt' }, hinweis: 'Unterbricht die individuelle Arbeit.' },
    wiederholung: { passung: 1, phasen: { 'Lücken bestimmen': 'kern', 'Sicherheit überprüfen': 'kern' }, hinweis: 'Die erste Abstimmung zeigt Lücken, die zweite den Lernzuwachs.' },
    vertieft: { passung: 4, phasen: { 'Problem erschließen': 'bedingt' }, hinweis: 'Höchstens als Einstieg vor der Teamarbeit.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Die erste Abstimmung ist eine schnelle Klassendiagnose.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil', 'Auswerten': 'teil' }, hinweis: 'Zeigt Fehlvorstellungen, aber nur im Gruppenbild.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Kein Einzelnachweis.' },
  },
};