// Didaktisches Grundmodell (Entwurf 2026-10-05): Stundenmodelle mit ihren Phasen.
export const STUNDEN_MODELLE = [
  { key: 'induktiv', name: 'Induktive Erarbeitung', phasen: ['Problem/Phänomen begegnen', 'Beobachten & erkunden', 'Vermutungen bilden', 'Vermutungen prüfen', 'Regel formulieren', 'Anwenden & sichern', 'Rückblick Erkenntnisweg'] },
  { key: 'deduktiv', name: 'Deduktive Erarbeitung', phasen: ['Vorwissen aktivieren / Ausgangsfrage', 'Regel einführen', 'Verstehen & klären', 'Angeleitetes Anwenden', 'Selbstständiger Transfer', 'Ergebnis sichern'] },
  { key: 'uebung_kurz', name: 'Individuelle Übung · kurz', phasen: ['Übungsfokus klären', 'Individuell üben', 'Lernstand kurz prüfen'] },
  { key: 'uebung_mittel', name: 'Individuelle Übung · mittel', phasen: ['Übungsfokus klären', 'Individuelle Arbeitsphase', 'Rückmeldung / Selbstkontrolle', 'Nächste Schritte'] },
  { key: 'uebung_lang', name: 'Individuelle Übung · lang', phasen: ['Arbeitsplan & Orientierung', 'Längere Übungszeit', 'Kontrolle & Korrektur', 'Abschlussbilanz'] },
  { key: 'wiederholung', name: 'Wiederholung', phasen: ['Vorwissen reaktivieren', 'Lücken bestimmen', 'Wiederholen & üben', 'Sicherheit überprüfen', 'Weiterführende Aufgabe', 'Abschlussreflexion'] },
  { key: 'vertieft', name: 'Vertiefte Übung', phasen: ['Aufgabe & Ziel klären', 'Problem erschließen', 'Lösungsideen entwickeln', 'Produkt erstellen', 'Vergleichen & präsentieren', 'Transfer reflektieren'] },
  { key: 'diagnose_kurz', name: 'Diagnose · kurz', phasen: ['Anlass & Kriterien klären', 'Lernstand erheben', 'Rückmelden / einordnen'] },
  { key: 'diagnose_mittel', name: 'Diagnose · mittel', phasen: ['Kriterien transparent machen', 'Lernstand erheben', 'Auswerten', 'Nächste Schritte'] },
  { key: 'diagnose_lang', name: 'Diagnose · lang', phasen: ['Ziel & Kriterien klären', 'Nachweise sammeln', 'Auswerten', 'Konsequenzen festlegen'] },
];

// 1 = passt hervorragend … 5 = passt nicht
export const PASSUNG = {
  1: { label: 'Passt hervorragend', cls: 'bg-green-600 text-white' },
  2: { label: 'Passt gut', cls: 'bg-green-200 text-green-900' },
  3: { label: 'Kann passen', cls: 'bg-yellow-200 text-yellow-900' },
  4: { label: 'Eher unpassend', cls: 'bg-orange-200 text-orange-900' },
  5: { label: 'Passt nicht', cls: 'bg-red-200 text-red-900' },
};

export const BEITRAG = { kern: 'Kernbeitrag', teil: 'Teilbeitrag', bedingt: 'Bedingt' };

// Probe-Einordnung, Schlüssel = Methodenname. phasen: { Phasenname: beitrag }
export const EINORDNUNG_PROBE = {
  'Informierender Unterrichtseinstieg': {
    induktiv: { passung: 3, phasen: { 'Problem/Phänomen begegnen': 'bedingt' }, hinweis: 'Nur den Ablauf erklären, die Erkenntnis nicht vorwegnehmen. Der Überraschungsmoment hat Vorrang.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Ziel, Regel und Ablauf einordnen.' },
    uebung_kurz: { passung: 3, phasen: { 'Übungsfokus klären': 'teil' }, hinweis: 'Eine knappe Zielklärung reicht.' },
    uebung_mittel: { passung: 2, phasen: { 'Übungsfokus klären': 'kern' }, hinweis: 'Aufgabenfolge, Wahlmöglichkeiten und Kontrollwege erklären.' },
    uebung_lang: { passung: 1, phasen: { 'Arbeitsplan & Orientierung': 'kern' }, hinweis: 'Bei Stationenlernen fast notwendig: Stationen, Zeit, Wechsel, Material, Ergebnis.' },
    wiederholung: { passung: 3, phasen: { 'Vorwissen reaktivieren': 'teil' }, hinweis: 'Sinnvoll bei Wahlaufgaben oder besonderem Ablauf.' },
    vertieft: { passung: 2, phasen: { 'Aufgabe & Ziel klären': 'teil' }, hinweis: 'Klärt Produkt und Zusammenarbeit, ersetzt aber nicht die Erschließung des Problems.' },
    diagnose_kurz: { passung: 2, phasen: { 'Anlass & Kriterien klären': 'kern' }, hinweis: 'Transparent machen, was erhoben wird und wozu.' },
    diagnose_mittel: { passung: 1, phasen: { 'Kriterien transparent machen': 'kern' }, hinweis: 'Ablauf und Kriterien erklären, ohne Lösungen vorwegzunehmen.' },
    diagnose_lang: { passung: 1, phasen: { 'Ziel & Kriterien klären': 'kern' }, hinweis: 'Bei mehreren Teilen oder Stationen fast notwendig.' },
  },
  'Stummer Impuls': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'bedingt' }, hinweis: 'Idealer überraschender Ausgangspunkt. Das Erkunden deckt er nur ab, wenn gezielte Beobachtungsaufträge folgen.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil' }, hinweis: 'Kann eine Leitfrage aufwerfen. Weniger passend, wenn die Stunde mit einer klaren Erklärung beginnt.' },
    uebung_kurz: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Höchstens als sehr kurzer Erinnerungsreiz, sonst kostet er Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Kann einen thematischen Rahmen setzen, ist aber kein Teil des Übens.' },
    uebung_lang: { passung: 3, phasen: { 'Arbeitsplan & Orientierung': 'bedingt' }, hinweis: 'Kann eine Anwendungssituation eröffnen, ersetzt aber nicht die Erklärung des Ablaufs.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Macht sichtbar, was erinnert wird und was unklar ist.' },
    vertieft: { passung: 2, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'teil' }, hinweis: 'Eröffnet einen Fall oder Konflikt als Ausgangspunkt für Teamarbeit.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Nur mit klarer Frage und nachvollziehbaren Kriterien als Diagnoseaufgabe nutzbar.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Als gemeinsamer Ausgangsreiz für eine Erhebung möglich.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Trägt eine umfassende Evaluation kaum, allenfalls als Einstieg in eine Teilaufgabe.' },
  },
  'Provokante These': {
    induktiv: { passung: 2, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Vermutungen bilden': 'teil' }, hinweis: 'Erzeugt Widerspruch und damit Fragebedarf. Die These darf die Regel nicht schon verraten.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern', 'Selbstständiger Transfer': 'bedingt' }, hinweis: 'Gute Ausgangsfrage, die die Regel anschließend klärt. Am Ende als Prüfstein für Transfer nutzbar.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Die Diskussion verbraucht die knappe Übungszeit.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Nur als kurzer Aufhänger, ohne ausführliche Debatte.' },
    uebung_lang: { passung: 4, phasen: { 'Arbeitsplan & Orientierung': 'bedingt' }, hinweis: 'Kann motivieren, trägt aber nichts zur Orientierung bei.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil' }, hinweis: 'Fehlvorstellungen werden beim Widerlegen sichtbar.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Ein starker Fall für die Teamarbeit. Am Ende wird die These erneut bewertet.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Zustimmung oder Ablehnung mit Begründung zeigt das Verständnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Als schriftliche Stellungnahme mit Kriterien nutzbar.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Als eine Teilaufgabe zur Argumentationsfähigkeit.' },
  },
  'Blitzlicht': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'teil', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Sammelt Vermutungen schnell ein oder schließt mit einem Rückblick ab.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil', 'Ergebnis sichern': 'bedingt' }, hinweis: 'Kurzer Stimmungs- oder Vorwissensabgleich, keine inhaltliche Sicherung.' },
    uebung_kurz: { passung: 3, phasen: { 'Lernstand kurz prüfen': 'teil' }, hinweis: 'Schnelle Selbsteinschätzung am Ende.' },
    uebung_mittel: { passung: 2, phasen: { 'Nächste Schritte': 'kern', 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Jeder benennt, wo er steht und was als Nächstes kommt.' },
    uebung_lang: { passung: 2, phasen: { 'Abschlussbilanz': 'kern' }, hinweis: 'Ritualisierter Abschluss einer langen Arbeitsphase.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'teil', 'Abschlussreflexion': 'kern' }, hinweis: 'Zeigt zu Beginn den Stand und am Ende den Zugewinn.' },
    vertieft: { passung: 2, phasen: { 'Transfer reflektieren': 'kern' }, hinweis: 'Reflexion der Teamarbeit und des Erkenntnisgewinns.' },
    diagnose_kurz: { passung: 2, phasen: { 'Rückmelden / einordnen': 'kern' }, hinweis: 'Selbsteinschätzung als Ergänzung zur Erhebung.' },
    diagnose_mittel: { passung: 3, phasen: { 'Nächste Schritte': 'teil' }, hinweis: 'Nur Selbsteinschätzung, kein belastbarer Nachweis.' },
    diagnose_lang: { passung: 4, phasen: { 'Konsequenzen festlegen': 'bedingt' }, hinweis: 'Zu oberflächlich für eine umfassende Diagnose.' },
  },
  'Brainstorming / Mindmap': {
    induktiv: { passung: 2, phasen: { 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'kern' }, hinweis: 'Sammelt Beobachtungen und Ideen, die Mindmap ordnet sie zu ersten Mustern.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern', 'Ergebnis sichern': 'teil' }, hinweis: 'Aktiviert Vorwissen. Als Mindmap zur Sicherung der Begriffsstruktur geeignet.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Höchstens als schnelle Begriffssammlung vorab.' },
    uebung_lang: { passung: 4, phasen: { 'Arbeitsplan & Orientierung': 'bedingt' }, hinweis: 'Trägt kaum zur Orientierung bei.' },
    wiederholung: { passung: 1, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'teil', 'Abschlussreflexion': 'bedingt' }, hinweis: 'Die Mindmap macht Zusammenhänge und fehlende Äste sichtbar.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'kern', 'Problem erschließen': 'teil' }, hinweis: 'Ideensammlung im Team vor der Produktion.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Eine Einzel-Mindmap zeigt die Wissensstruktur.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Braucht klare Kriterien für die Auswertung.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Vorher-Nachher-Mindmap als Lernnachweis.' },
  },
  'Vertieftes Üben im Team': {
    induktiv: { passung: 4, phasen: { 'Vermutungen prüfen': 'bedingt', 'Anwenden & sichern': 'bedingt' }, hinweis: 'Zu umfangreich für eine Erarbeitungsstunde, allenfalls als Anwendungsteil.' },
    deduktiv: { passung: 3, phasen: { 'Selbstständiger Transfer': 'teil', 'Angeleitetes Anwenden': 'bedingt' }, hinweis: 'Kann den Transfer übernehmen, wenn die Regel gesichert ist.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 4, phasen: { 'Individuelle Arbeitsphase': 'bedingt' }, hinweis: 'Teamarbeit statt individueller Übung, nur in verkürzter Form.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil' }, hinweis: 'Möglich, wenn kooperatives Üben gewünscht ist.' },
    wiederholung: { passung: 3, phasen: { 'Wiederholen & üben': 'teil', 'Weiterführende Aufgabe': 'teil' }, hinweis: 'Sinnvoll als weiterführender Teil einer Wiederholung.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'kern', 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'kern', 'Produkt erstellen': 'kern', 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'teil' }, hinweis: 'Trägt die ganze Stunde. Das Preset bestimmt den Ablauf der Phasen.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 5, phasen: {}, hinweis: 'Gruppenprodukte zeigen keinen individuellen Lernstand.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Nur mit zusätzlicher Einzelleistung als Nachweis nutzbar.' },
  },
  'Kartenabfrage': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'kern', 'Regel formulieren': 'teil' }, hinweis: 'Das Clustern der Karten führt zur Regel hin.' },
    deduktiv: { passung: 2, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Strukturierte Vorwissenserhebung vor der Erklärung.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Zu aufwendig für kurze Übungen.' },
    uebung_mittel: { passung: 4, phasen: { 'Nächste Schritte': 'bedingt' }, hinweis: 'Allenfalls zum Sammeln offener Fragen.' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Sammelt Schwierigkeiten und Erkenntnisse am Ende.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Lücken bestimmen': 'kern' }, hinweis: 'Anonyme Karten machen Unsicherheiten sichtbar.' },
    vertieft: { passung: 2, phasen: { 'Lösungsideen entwickeln': 'teil', 'Vergleichen & präsentieren': 'teil' }, hinweis: 'Ordnet Ideen oder Ergebnisse mehrerer Teams.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Gibt ein Gruppenbild, kein Einzelergebnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Auswerten': 'teil' }, hinweis: 'Gemeinsame Auswertung von Schwierigkeiten.' },
    diagnose_lang: { passung: 3, phasen: { 'Konsequenzen festlegen': 'teil' }, hinweis: 'Gemeinsames Ableiten nächster Schritte.' },
  },
  'Vertieftes Üben im Team mit Ämtern': {
    induktiv: { passung: 5, phasen: {}, hinweis: 'Ämterverteilung und Teamprozess sprengen eine Erarbeitungsstunde.' },
    deduktiv: { passung: 4, phasen: { 'Selbstständiger Transfer': 'bedingt' }, hinweis: 'Nur als ausgelagerter Transferteil, wenn die Regel bereits sicher ist.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Passt zeitlich nicht.' },
    uebung_mittel: { passung: 5, phasen: {}, hinweis: 'Die Organisation der Ämter kostet zu viel Übungszeit.' },
    uebung_lang: { passung: 3, phasen: { 'Längere Übungszeit': 'teil', 'Abschlussbilanz': 'bedingt' }, hinweis: 'Möglich bei kooperativem Üben über mehrere Stunden.' },
    wiederholung: { passung: 4, phasen: { 'Weiterführende Aufgabe': 'bedingt' }, hinweis: 'Für eine Wiederholung meist zu aufwendig.' },
    vertieft: { passung: 1, phasen: { 'Aufgabe & Ziel klären': 'kern', 'Problem erschließen': 'kern', 'Lösungsideen entwickeln': 'kern', 'Produkt erstellen': 'kern', 'Vergleichen & präsentieren': 'kern', 'Transfer reflektieren': 'kern' }, hinweis: 'Trägt die ganze Stunde. Die Ämter sichern Arbeitsteilung und Reflexion des Teamprozesses.' },
    diagnose_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Diagnoseformat.' },
    diagnose_mittel: { passung: 5, phasen: {}, hinweis: 'Gruppenprodukte zeigen keinen individuellen Lernstand.' },
    diagnose_lang: { passung: 3, phasen: { 'Nachweise sammeln': 'teil' }, hinweis: 'Ämter machen Einzelbeiträge sichtbar, z. B. für Sozial- und Methodenkompetenz.' },
  },
  'Positionslinie / Meinungsbarometer': {
    induktiv: { passung: 3, phasen: { 'Vermutungen bilden': 'kern', 'Rückblick Erkenntnisweg': 'teil' }, hinweis: 'Schüler positionieren sich zu einer Vermutung und prüfen am Ende, ob sie umziehen würden.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'kern' }, hinweis: 'Macht Vorannahmen sichtbar, bevor die Regel eingeführt wird.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil', 'Nächste Schritte': 'teil' }, hinweis: 'Als Selbsteinschätzung: Wie sicher fühle ich mich?' },
    uebung_lang: { passung: 3, phasen: { 'Abschlussbilanz': 'teil' }, hinweis: 'Schnelles, sichtbares Stimmungsbild am Ende.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'teil', 'Lücken bestimmen': 'kern' }, hinweis: 'Zeigt auf einen Blick, wo die Gruppe unsicher ist.' },
    vertieft: { passung: 2, phasen: { 'Problem erschließen': 'teil', 'Transfer reflektieren': 'kern' }, hinweis: 'Vorher-Nachher-Positionierung zeigt, ob die Teamarbeit Meinungen verändert hat.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'teil', 'Rückmelden / einordnen': 'teil' }, hinweis: 'Schnelle Selbsteinschätzung der ganzen Gruppe.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'bedingt' }, hinweis: 'Nur mit Begründungen ein brauchbarer Nachweis.' },
    diagnose_lang: { passung: 4, phasen: { 'Konsequenzen festlegen': 'bedingt' }, hinweis: 'Zu grob für eine umfassende Diagnose.' },
  },
  'Vier-Ecken-Methode': {
    induktiv: { passung: 2, phasen: { 'Vermutungen bilden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Jede Ecke steht für eine Vermutung. Die Gruppen sammeln Argumente und prüfen sie.' },
    deduktiv: { passung: 3, phasen: { 'Vorwissen aktivieren / Ausgangsfrage': 'teil', 'Verstehen & klären': 'bedingt' }, hinweis: 'Ecken als Antwortoptionen machen Fehlvorstellungen vor der Erklärung sichtbar.' },
    uebung_kurz: { passung: 4, phasen: { 'Lernstand kurz prüfen': 'bedingt' }, hinweis: 'Höchstens als schnelle Multiple-Choice-Abfrage im Raum.' },
    uebung_mittel: { passung: 3, phasen: { 'Rückmeldung / Selbstkontrolle': 'teil' }, hinweis: 'Als bewegte Kontrollfrage mit Begründung.' },
    uebung_lang: { passung: 4, phasen: { 'Kontrolle & Korrektur': 'bedingt' }, hinweis: 'Unterbricht die lange Übungszeit eher.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Sicherheit überprüfen': 'teil' }, hinweis: 'Antwortecken zeigen schnell, welche Inhalte sitzen.' },
    vertieft: { passung: 3, phasen: { 'Problem erschließen': 'teil', 'Lösungsideen entwickeln': 'bedingt' }, hinweis: 'Kann Teams nach Position bilden, bevor die Teamarbeit beginnt.' },
    diagnose_kurz: { passung: 2, phasen: { 'Lernstand erheben': 'kern' }, hinweis: 'Gute Schnelldiagnose, wenn die Ecken typische Fehler abbilden.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Ergänzt eine schriftliche Erhebung.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Liefert keine individuellen Nachweise.' },
  },
  'Think-Pair-Share': {
    induktiv: { passung: 1, phasen: { 'Beobachten & erkunden': 'teil', 'Vermutungen bilden': 'kern', 'Regel formulieren': 'kern' }, hinweis: 'Jeder denkt erst allein nach, dann wird im Paar verdichtet und im Plenum zur Regel geführt.' },
    deduktiv: { passung: 2, phasen: { 'Verstehen & klären': 'kern', 'Angeleitetes Anwenden': 'teil' }, hinweis: 'Sichert das Verständnis der eingeführten Regel.' },
    uebung_kurz: { passung: 4, phasen: { 'Lernstand kurz prüfen': 'bedingt' }, hinweis: 'Für reine Übung meist zu viel Austausch.' },
    uebung_mittel: { passung: 2, phasen: { 'Individuelle Arbeitsphase': 'teil', 'Rückmeldung / Selbstkontrolle': 'kern' }, hinweis: 'Erst allein üben, dann Ergebnisse im Paar vergleichen.' },
    uebung_lang: { passung: 2, phasen: { 'Längere Übungszeit': 'teil', 'Kontrolle & Korrektur': 'kern' }, hinweis: 'Partnerkontrolle strukturiert die Korrektur.' },
    wiederholung: { passung: 2, phasen: { 'Vorwissen reaktivieren': 'kern', 'Wiederholen & üben': 'teil' }, hinweis: 'Gegenseitiges Erklären festigt das Wissen.' },
    vertieft: { passung: 2, phasen: { 'Problem erschließen': 'teil', 'Lösungsideen entwickeln': 'kern' }, hinweis: 'Gute Vorstufe vor der Teamarbeit.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Die Think-Phase liefert ein Einzelergebnis.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil', 'Auswerten': 'teil' }, hinweis: 'Paarweise Auswertung mit Kriterien möglich.' },
    diagnose_lang: { passung: 4, phasen: { 'Auswerten': 'bedingt' }, hinweis: 'Trägt eine umfassende Diagnose nicht.' },
  },
  'Demonstration / Experiment vorführen': {
    induktiv: { passung: 1, phasen: { 'Problem/Phänomen begegnen': 'kern', 'Beobachten & erkunden': 'kern', 'Vermutungen prüfen': 'teil' }, hinweis: 'Das Phänomen wird sichtbar. Vorher Vermutungen sammeln, damit die Beobachtung gezielt wird.' },
    deduktiv: { passung: 2, phasen: { 'Regel einführen': 'teil', 'Verstehen & klären': 'kern' }, hinweis: 'Veranschaulicht und bestätigt die eingeführte Regel.' },
    uebung_kurz: { passung: 5, phasen: {}, hinweis: 'Kein Übungsformat.' },
    uebung_mittel: { passung: 4, phasen: { 'Übungsfokus klären': 'bedingt' }, hinweis: 'Höchstens als kurzes Vormachen der Arbeitstechnik.' },
    uebung_lang: { passung: 3, phasen: { 'Arbeitsplan & Orientierung': 'teil' }, hinweis: 'Vormachen eines Verfahrens, das danach selbst geübt wird.' },
    wiederholung: { passung: 3, phasen: { 'Vorwissen reaktivieren': 'teil' }, hinweis: 'Erneutes Zeigen ruft Wissen wach.' },
    vertieft: { passung: 3, phasen: { 'Aufgabe & Ziel klären': 'teil', 'Problem erschließen': 'teil' }, hinweis: 'Kann den Ausgangsfall der Teamarbeit liefern.' },
    diagnose_kurz: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Schüler erklären ein vorgeführtes Phänomen.' },
    diagnose_mittel: { passung: 3, phasen: { 'Lernstand erheben': 'teil' }, hinweis: 'Als Erklärungsaufgabe mit Kriterien nutzbar.' },
    diagnose_lang: { passung: 4, phasen: { 'Nachweise sammeln': 'bedingt' }, hinweis: 'Allenfalls Teil einer Gesamtdiagnose.' },
  },
};